### ISSUE TITLE
Errors when using complex filters

### ISSUE THREAD

**Issue by marcograwunder** [rde-master/ioBroker.todoist2#13]
Thank you for your great work. 

I found an error, that should be easy to fix. ToDoIst allows to use filters. Everything works fine, when you just use something like (today) but there is also the possibility to use something like (today & #Project). In this case, there is a 400 response (Bad Request). This is because the characters are directly send via the REST call. When I use (today%20%26%20%23Project) everything works fine. So, there should be a decoding of the URL parameter.

**Comment by rde-master** [comment]
The bug was fixed in version 0.8.7, you can now test it.

**Comment by marcograwunder** [comment]
Thank you! Works now as expected!
