### ISSUE TITLE
Send.to date geht nicht

### ISSUE THREAD

**Issue by fabiankrauss** [rde-master/ioBroker.todoist2#14]
Hallo danke erstmal für den coolen Adapter!

Meine Frage ist, ob ich das date bei send.to falsch nutze oder hier ein Bug vorliegt?

vielleicht wurde hier die API zu due_string, due_date, due_datetime und due_lang geändert?
Könntest du dir das mal ansehen?

Danke!

**Comment by rde-master** [comment]
Hallo, 
ja, kann ich bestätigen, da hat sich an der API was geändert.

Ich bin dran, und werde eine neue Version rausbringen.

**Comment by rde-master** [comment]
Bug ist gefixt. Neue Version wird bereitgestellt

**Comment by fabiankrauss** [comment]
@rde-master  Habe die neu Version getestet und due_string funktioniert ohne Probleme! Das wäre super in der Doku zu ergänzen. Mit due_date im Format JJJJ-MM-TT klappt es bis jetzt noch nicht. Aber vielleicht sitzt hier das Problem auch vor dem Bildschirm.

**Comment by rde-master** [comment]
@fabiankrauss 
Also bei mir geht auch das Datum in dem Format.
wo nutzt du genau die Funktion? über die Objekte "Control" oder im script?
