### ISSUE TITLE
Error der zu Reboot Loop führt ohne Änderungen im Setup

### ISSUE THREAD

**Issue by Claus1985** [rde-master/ioBroker.todoist2#15]
Hi,

erstmal vielen Dank für den klasse Adapter. Nutze ihn schon einige Monate ohne Probleme.
Seit etwa einer Woche funktioniert der Adapter allerdings nicht mehr - ohne das am Setup etwas geändert wurde.
Er läuft immer wieder in den gleichen Error und erzeugt damit einen Boot-Loop.
Im Debug-Log steht folgendes:
`
<html>
<body>

todoist2.0 | 2021-08-31 12:47:41.993 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
todoist2.0 | 2021-08-31 12:47:41.992 | info | terminating
todoist2.0 | 2021-08-31 12:47:41.991 | info | cleaned everything up...
todoist2.0 | 2021-08-31 12:47:41.988 | error | Cannot read property 'length' of undefined
todoist2.0 | 2021-08-31 12:47:41.987 | error | TypeError: Cannot read property 'length' of undefined at tasktolabels (/opt/iobroker/node_modules/iobroker.todoist2/main.js:1968:26) at main (/opt/iobroker/node_modules/iobroker.todoist2/main.js:3009:13)
todoist2.0 | 2021-08-31 12:47:41.985 | error | unhandled promise rejection: Cannot read property 'length' of undefined
todoist2.0 | 2021-08-31 12:47:41.984 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
todoist2.0 | 2021-08-31 12:47:40.667 | info | starting. Version 0.8.7 in /opt/iobroker/node_modules/iobroker.todoist2, node: v12.22.2, js-controller: 3.3.14
todoist2.0 | 2021-08-31 12:47:40.474 | debug | statesDB connected
todoist2.0 | 2021-08-31 12:47:40.473 | debug | States connected to redis: 127.0.0.1:6379
todoist2.0 | 2021-08-31 12:47:40.464 | debug | States create User PubSub Client
todoist2.0 | 2021-08-31 12:47:40.463 | debug | States create System PubSub Client
todoist2.0 | 2021-08-31 12:47:40.455 | debug | Redis States: Use Redis connection: 127.0.0.1:6379
todoist2.0 | 2021-08-31 12:47:40.452 | debug | objectDB connected
todoist2.0 | 2021-08-31 12:47:40.443 | debug | Objects connected to redis: 127.0.0.1:9001
todoist2.0 | 2021-08-31 12:47:40.422 | debug | Objects client initialize lua scripts
todoist2.0 | 2021-08-31 12:47:40.420 | debug | Objects create User PubSub Client
todoist2.0 | 2021-08-31 12:47:40.419 | debug | Objects create System PubSub Client
todoist2.0 | 2021-08-31 12:47:40.417 | debug | Objects client ready ... initialize now
todoist2.0 | 2021-08-31 12:47:40.382 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
host.Schaltzentrale2 | 2021-08-31 12:47:39.402 | info | instance system.adapter.todoist2.0 started with pid 19059

</body>
</html>`

Woran könnte das liegen?

Vielen Dank und viele Grüße,

Claus

**Comment by rde-master** [comment]
Hallo Claus,

kannst du in den Einstellungen mal bitte die Labels ausschalten.
Funktioniert es dann?

Grüße

**Comment by Claus1985** [comment]
Funktioniert ohne Labels einwandfrei, da ich diese Funktion nicht benötige perfekt! 😊👌🏼 
vielen Dank für den Tip!
Viele Grüße Claus

**Comment by rde-master** [comment]
ah ok, dann vermute ich, dass du gar keine labels definiert hast,.. und damit kommt der Fehler.
Ich schau dass ich da eine Prüfung einbaue.
