### ISSUE TITLE
Filter Abfrage zeigt nur eine Ausgabe

### ISSUE THREAD

**Issue by dominikkerkow** [rde-master/ioBroker.todoist2#17]
Die Filterabfrage "today & ##PRIVAT" - also alles heutige und in dem Projekt und den Unterprojekten aus PRIVAT funktioniert nicht korrekt. Es wird in der JSON und TXT Abfrage nur ein Item angezeigt, obwohl es mehr als 6 gibt. In der HTML Abfrage kommt auch nur das eine Item, aber so oft, wieviele Einträge es geben sollte.
Ich habe einen Todoist Premium Account und die installierte Version 0.8.7

**Comment by rde-master** [comment]
Die aktuelle Version ist die 0.8.9 kannst du diese bitte Testen, da sollte der Fehler behoben sein

**Comment by dominikkerkow** [comment]
Habe die 0.8.9 installiert. Adapter beendet und neu gestartet. Gleiches Bild wie bisher. Soll ich einen Cache o.ä. löschen? Biobroker komplett neu starten?

**Comment by rde-master** [comment]
Hmm,... die Eingabe wird ungefiltert an Todoist übertragen.
Bist du dir sicher dass es 2# sein müssen? Bei mir ist es nur ein #

**Comment by dominikkerkow** [comment]
Wenn ich heute in Todoist einen Filter anlege und denselben Inhalt wie im Adapter eintrage, kommen drei Einträge.

In den Listen TXT und JSON kommt jeweils nur ein Eintrag an. In der HTML Variante kommen drei Einträge an, aber alle mit dem einen Eintrag und der einen ID, wie auch bei TXT und JSON.
Also "reagiert" wohl die HTML Aufbereitung und Ausgabe besser / richtig, aber zeigt nur die erste gefundene ID in allen Einträgen an.

Was brauchst Du, um dies weiter nachvollziehen zu können?

**Comment by rde-master** [comment]
Dann brauch ich bitte deine Debug logs.
Bitte deaktiviere in den Einstellungen mal bei "Auswahl von Objekten" alle 4 Punkte.
Und bei Art nur den Text an.
Dann noch den Hacken bei Debug.

Dann sollte er alles was zu den Filtern gehört an debug info auswerfen.

Dann kann ich nachvollziehen was die Schleifen denn machen um die Text liste zu erzeugen.

**Comment by dominikkerkow** [comment]
Habe dies umgesetzt.
Wie lange soll ich das laufen lassen, vermute die nachfolgende Ausgabe ist zu wenig:



```
todoist2.0 | 2021-11-25 13:12:34.552 | debug | statesDB connected
-- | -- | -- | --
todoist2.0 | 2021-11-25 13:12:34.551 | debug | States connected to redis: 127.0.0.1:9000
todoist2.0 | 2021-11-25 13:12:34.539 | debug | States create User PubSub Client
todoist2.0 | 2021-11-25 13:12:34.538 | debug | States create System PubSub Client
todoist2.0 | 2021-11-25 13:12:34.528 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
todoist2.0 | 2021-11-25 13:12:34.526 | debug | objectDB connected
todoist2.0 | 2021-11-25 13:12:34.517 | debug | Objects connected to redis: 127.0.0.1:9001
todoist2.0 | 2021-11-25 13:12:34.499 | debug | Objects client initialize lua scripts
todoist2.0 | 2021-11-25 13:12:34.498 | debug | Objects create User PubSub Client
todoist2.0 | 2021-11-25 13:12:34.497 | debug | Objects create System PubSub Client
todoist2.0 | 2021-11-25 13:12:34.495 | debug | Objects client ready ... initialize now
todoist2.0 | 2021-11-25 13:12:34.461 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
```

**Comment by rde-master** [comment]
Ohje, da fehlen aber einige Logs.
Das sind ja nur die Standard vom ioBroker selbst.
Das Log muss im diesem Modus total voll werden, weil jeder Schritt im Log erscheint.

Und den Debug Modus in den Einstellung von Todoist hast du auch an?

**Comment by dominikkerkow** [comment]
Den Debug Modus hatte ich an. Vermute aber, dass ich das falsche Log verwendet habe.
Wie kann ich das Log exportieren?

Habe zwischenzeitlich alles von todoist2 entfernt, alles nochmals neu installiert - keine Änderung. Gleicher Sachverhalt.

Freue mich auf Deine Rückmeldung, damit ich gut unterstützen kann.

**Comment by rde-master** [comment]
Ich habe gute Nachrichten.
Ich konnte den Fehler finden (der war echt gut versteckt :-)

die neue Version 0.8.10 sollte den fehler beheben.

Kannst du diese bitte testen.

**Comment by dominikkerkow** [comment]
Funktioniert tadellos! Vielen Dank
