### ISSUE TITLE
JSON Filter List Task ID, eine weitere ID und Parent ID gleiche Section Bezeichnung

### ISSUE THREAD

**Issue by dominikkerkow** [rde-master/ioBroker.todoist2#18]
Hallo,
leider weisen alle drei IDs in der JSON List den Name "ID" auf. Somit ist es unmöglich, die ID des Tasks bspw. abzurufen und eine Funktion (erledigt) darauf per Button zu definieren. Nachfolgend die Beispiele:

`[{"Task":"Aufgabe 1","ID","4138142213","priority":"1","ID":"0","ID":"undefined"}]`

Eingestellt in den JSON Einstellungen ist jeweils ein anderer Name, welcher aber nicht genutzt wird.

**Comment by rde-master** [comment]
Hallo,

Danke für den Hinweis!
Hab den Fehler auch schon gefunden.
Ich bereite einen Fix vor.

**Comment by rde-master** [comment]
Fix ist da, uns sollte über Nacht auch als Update im ioBroker kommen.
Dann bitte nochmals testen.
(War ein einfacher Coppy / Paste Fehler)

**Comment by dominikkerkow** [comment]
Super. Danke!
Ich melde mich nach dem erneuten Test. 

Ist es möglich, zugewiesene Personen und die Uhrzeit der Tasks noch zu bekommen?

**Comment by dominikkerkow** [comment]
Gibt noch kein Update im ioBroker. Schaue später nochmals nach.

**Comment by rde-master** [comment]
Personen und Datum usw. sind in Version 0.9 drin.
