### ISSUE TITLE
Projekt mit "." im Titel wird zu Ordner

### ISSUE THREAD

**Issue by adcrafter27** [rde-master/ioBroker.todoist2#3]
Hallo ich habe in meinen Projekt namen Punkte verwendet (datum)
Dies wird im ioBroker als Ordner angezeigt und ist leer obwohl 9 bzw 5 aufgaben enthalten sind

![image](https://user-images.githubusercontent.com/15692264/75577607-a339f200-5a62-11ea-9b46-a397d7cdb360.png)

![image](https://user-images.githubusercontent.com/15692264/75577629-ad5bf080-5a62-11ea-936f-4cc3410d4d3f.png)

**Comment by rde-master** [comment]
Sollte nun behoben sein.

**Comment by adcrafter27** [comment]
Danke Fehler ist nun behoben nun wird aus "." ein "-" gemacht, eine sehr gute Lösung
