### ISSUE TITLE
JSON Format Falsch?

### ISSUE THREAD

**Issue by adcrafter27** [rde-master/ioBroker.todoist2#4]
Hallo
Kenne mich nicht so gut aus aber ich glaube die JSON Ausgabe bei Projects-JSON sind falsch.
sonst berichtige mich bitte, bin ja noch am lernen.

sollte der wert nicht so aussehen wie du es bei JSON-Projects gelöst hast? mit "[" und "]" und die einzelnen Positionen durch ein "," trennen? 
damit man sie durch "nummerieren" kann? [0],[1]....

JSON-Projects:

[{"id":xxxx,"color":48,"name":"Inbox","comment_count":0,"shared":false,"inbox_project":true},{"id":xxxxx,"order":1,"color":31,"name":"test","comment_count":0,"shared":false},{"id":xxxxx,"order":2,"color":36,"name":"test Privat","comment_count":0,"shared":false},{"id":xxxxxx,"order":3,"color":32,"name":"Alexa To-do List","comment_count":0,"shared":false}]

Projects-JSON:

Tasks{"id":xxxxx,"project_id":xxxxx,"section_id":0,"order":1,"content":"Test1","completed":false,"label_ids":[xxxxx],"priority":1,"comment_count":0,"created":"2020-02-28T13:25:53Z","url":"https://todoist.com/showTask?id=xxxxx&sync_id=xxxxx"}

{"id":xxxxxx,"project_id":xxxxx,"section_id":0,"order":2,"content":"Test","completed":false,"label_ids":[xxxxx],"priority":1,"comment_count":0,"created":"2020-02-28T13:26:08Z","url":"https://todoist.com/showTask?id=xxxxxx&sync_id=xxxxxx"}

**Comment by rde-master** [comment]
Ja an den JSON Datenpunkten bin ich noch dran.
Steht sozusagen als nächstes auf der Todo Liste.
Ich hab den Adapter auch deshalb noch nicht ins Forum veröffentlicht, da ich hier noch fleißig am erweitern bin.
Wenn du weitere Punkte / Wünsche hast, aber gerne schonmal her damit.

**Comment by adcrafter27** [comment]
Sehr gut.
Ich persönlich hätte schon einen Wunsch
zwar die einzelnen Positionen (Namen) in text form mittels "," getrennt (zbs bei Alexa-Einkaufsliste)

Apfel, Birne, Nudel, Essig, ......

**Comment by rde-master** [comment]
So die JSON Datenpunkte erstelle ich jetzt alle selber, und importiere nicht mehr direkt von der API, das sollte das Problem lösen.
Ebenfalls ist die Text Ansicht drin.

Da ich die Objekte neu anordne musst du einmal alles löschen und neu von Github anlegen.
Dann sollte alles klappen.
In den Adapter Einstellungen kannst du alles Einstellen was du erzeugt haben willst.

**Comment by adcrafter27** [comment]
Danke, echt sehr gut umgesetzt jetzt funktioniert es wie gewünscht :) und noch besser dank den zusätzlichen Einstellungen.
Ich denke so wie es jetzt ist kannst du es veröffentlichen
