### ISSUE TITLE
Fehler beim speichern nach Änderungen

### ISSUE THREAD

**Issue by adcrafter27** [rde-master/ioBroker.todoist2#5]
Wenn ich nachträglich noch eine Veränderung an den Adapter Einstellungen vornehme (zbs einen hacken raus Name von Section) kann ich diese Einstellung nicht speichern (speichern bleibt grau)

Speichern ist nur möglich wen man etwas am Token oder polling interval ändert

**Comment by rde-master** [comment]
Fehler gefunden und behoben.

**Comment by adcrafter27** [comment]
Danke ist behoben
