### ISSUE TITLE
Frage bzgl. Task-ID

### ISSUE THREAD

**Issue by Claus1985** [rde-master/ioBroker.todoist2#7]
Hallo, 
erstmal vielen Dank für den genialen Adapter! 
Eine Frage zur Task-ID. Muss ich diese mitgeben oder wird die autom. erzeugt?
Wenn ich die mitgeben muss, was muss ich dabei beachten?

Vielen Dank!

**Comment by rde-master** [comment]
Die Task ID kommt von Todoist und wird für jeden Task von denen generiert. Es ist also eine eindeutige ID für jeden Task.

Für viele Funktionen will die API diese ID haben. Z.b. um einen task zu erledigen musst du die ID mitgeben.

Die ID kannst du dir manuell anziehen lassen indem du dir die einzelnen Tasks als Objekte anlegen lässt (kannst du in den Einstellungen wählen)

Oder in den JSON Objekten sind die IDs auch mit drin in diese in Skripten zu verarbeiten.

**Comment by Claus1985** [comment]
Danke für die schnelle Antwort. D.h. um einen Task anzulegen muss ich keine ID mitgeben?
